volumes:
  elasticsearch_data:
    driver: local
  grafana_data:
    driver: local

networks:
  dmarc_visualizer:

services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./parsedmarc/output_files:/output
    command: sh -c "crond && parsedmarc --verbose --debug -c /parsedmarc.ini /input/*"
    restart: always
    networks:
      - dmarc_visualizer
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      -

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    expose:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - dmarc_visualizer
    environment:
      - cluster.name=dmarc_visualizer
      - cluster.max_shards_per_node=2555
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

  grafana:
    build: ./grafana/
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - dmarc_visualizer
    # user: grafana
    environment:
      GF_LOG_LEVEL: debug
      # GF_SERVER_ROOT_URL: ''

      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin1"
      # GF_SECURITY_ADMIN_EMAIL: ''
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      # GF_SECURITY_COOKIE_SECURE: 'true'
      GF_SECURITY_ANGULAR_SUPPORT_ENABLED: "false"

      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/Grafana-DMARC_Reports.json"

      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_BASIC: "true"

      # GF_AUTH_AZUREAD_AUTO_LOGIN: 'false'
      # GF_AUTH_AZUREAD_ENABLED: 'false'
      # GF_AUTH_AZUREAD_ALLOW_SIGN_UP: 'false'
      # GF_AUTH_AZUREAD_CLIENT_ID: ''
      # GF_AUTH_AZUREAD_CLIENT_SECRET: ''
      # GF_AUTH_AZUREAD_SCOPES: openid email profile
      # GF_AUTH_AZUREAD_AUTH_URL: ''
      # GF_AUTH_AZUREAD_TOKEN_URL: ''
      # GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT: 'false'
      # GF_AUTH_AZUREAD_ALLOW_ASSIGN_GRAFANA_ADMIN: 'false'

      GF_UNIFIED_ALERTING_ENABLED: "false"

      GF_ALERTING_ENABLED: "false"

      GF_EXPLORE_ENABLED: "false"

      GF_DATE_FORMATS_USE_BROWSER_LOCALE: "true"
      GF_DATE_FORMATS_DEFAULT_TIMEZONE: "browser"
      GF_DATE_FORMATS_DEFAULT_WEEK_START: "monday"
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
